<a href="https://colab.research.google.com/github/vidya051/internship/blob/master/numpy%20basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
b=np.arange(3)
b

array([0, 1, 2])

In [5]:
c=np.exp(b)
c

array([1.        , 2.71828183, 7.3890561 ])

In [6]:
d=np.sqrt(b)
d

array([0.        , 1.        , 1.41421356])

In [7]:
C = np.array([2., -1., 4.])
np.add(b, C)

array([2., 0., 6.])

In [8]:
e = np.arange(5)**3
e

array([ 0,  1,  8, 27, 64])

In [10]:
e[2]

8

In [11]:
e[2:5]

array([ 8, 27, 64])

In [12]:
v=np.arange(2)
v

array([0, 1])

In [15]:
v[:6:2]=-1000
v

array([-1000,     1])

In [16]:
v[: : -1]

array([    1, -1000])

In [20]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [22]:
a[:6:2]=-1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729])

In [24]:
a[: :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000])

In [26]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in power
  


In [29]:
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [30]:
np.array(8)

array(8)

In [32]:
np.array([2,3])

array([2, 3])

In [33]:
np.array([1,2,3])

array([1, 2, 3])

In [36]:
d3_array = np.array([[[0, 1],
                       [2, 3]],

                       [[4, 5],
                       [6, 7]]])
d3_array

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
d3_array.ndim

3

In [41]:
d3_array[0,1,1]

3

In [44]:
d3_array[1,0,1]

5

In [46]:
d3_array[1]


array([[4, 5],
       [6, 7]])

In [53]:
vn=np.array([[[1,2,3],
               [5,3,1]],
               [[5,6,3],
              [3,5,8]]])
vn         

array([[[1, 2, 3],
        [5, 3, 1]],

       [[5, 6, 3],
        [3, 5, 8]]])

In [55]:
x = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
               [ 9, 10, 11, 12]])

x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
x.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [57]:
x.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [59]:
x = np.array([0, 1, 2, 3, 4, 5])
x

array([0, 1, 2, 3, 4, 5])

In [60]:
x.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
a = np.floor(10*np.random.random((3,4)))
a

array([[6., 6., 2., 6.],
       [5., 7., 0., 5.],
       [4., 1., 2., 2.]])

In [62]:
a.shape

(3, 4)

(3, 4)

In [64]:
a.ravel()  

array([6., 6., 2., 6., 5., 7., 0., 5., 4., 1., 2., 2.])

In [65]:
a.resize((2,6))
a


array([[6., 6., 2., 6., 5., 7.],
       [0., 5., 4., 1., 2., 2.]])

In [66]:
 a = np.floor(10*np.random.random((2,2)))
 a

array([[5., 6.],
       [7., 6.]])

In [67]:
 b = np.floor(10*np.random.random((2,2)))
 b

array([[1., 9.],
       [4., 3.]])