<a href="https://colab.research.google.com/github/vidya051/internship/blob/master/python%20func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [3]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [4]:
np.linalg.inv(a)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
u = np.eye(2) 
u

array([[1., 0.],
       [0., 1.]])

In [6]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j

array([[ 0., -1.],
       [ 1.,  0.]])

In [7]:
j@j


array([[-1.,  0.],
       [ 0., -1.]])

In [8]:
y = np.array([[5.], [7.]])
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [9]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [12]:
from array import *
my_array = array('i', [1,2,3,4,5])
for i in my_array:
  print(i)

1
2
3
4
5


In [13]:
my_array.append(6)
my_array

array('i', [1, 2, 3, 4, 5, 6])

In [14]:
my_array.insert(0,0)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6])

In [15]:
 my_extnd_array = array('i', [7,8,9,10])
my_array.extend(my_extnd_array)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [16]:
c=[11,12,13]
my_array.fromlist(c)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

In [17]:
my_array.remove(13)
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [18]:
my_array.pop()

12

In [19]:
my_array.pop(6)

6

In [20]:
my_array

array('i', [0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11])

In [21]:
my_array.index(5)

5

In [0]:
my_array.insert(6,6)

In [25]:
my_array

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [26]:
my_array.reverse()
my_array

array('i', [11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
my_array.buffer_info()

(140042554437392, 12)

In [30]:
my_array.count(10)

1

In [32]:
my_char_array = array('c', [ord('g'),ord('e'),ord('e'),ord('k')])
my_char_array

ValueError: ignored

In [38]:
def is_prime(n):
  for i in range(2, n):
    if n % i == 0:
      return False
  return True
n = input("Enter a number: ")
for x in range(2, int(n)):
  if is_prime(x):
    print(x, " is prime")
  else:
    print(x, " is not prime")

Enter a number: 10
2  is prime
3  is prime
4  is not prime
5  is prime
6  is not prime
7  is prime
8  is not prime
9  is not prime


In [42]:
n=int(input("enter the prime num"))
if n>1:
  for i in range (2,n):
    if n%i==0:
      print(n,"not prime")
    else:
      print(n,"prime")

enter the prime num4
4 not prime
4 prime


In [46]:

list1 = [10, 21, 4, 45, 66, 93, 1] 
  
even,odd= 0, 0
  

for num in list1: 
      
   
    if num % 2 == 0: 
        even += 1
  
    else: 
        odd += 1
          
print("Even numbers in the list: ", even) 
print("Odd numbers in the list: ", odd) 


Even numbers in the list:  3
Odd numbers in the list:  4


In [48]:
num = int(input("Enter a number: "))
mod = num % 2
if mod > 0:
    print("This is an odd number.")
else:
    print("This is an even number.")

Enter a number: 31
This is an odd number.
